version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: scandinavian-name-corrector:latest
    container_name: name-corrector-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./indices:/app/indices
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
      - DEBUG=False
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/server"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - name-corrector-network

networks:
  name-corrector-network:
    driver: bridge